[tool.isort]
profile = "black"
include_trailing_comma = true

known_future_library = ["future", "__future__"]
known_django = ["django"]
import_heading_stdlib = "Standard libraries"
import_heading_django = "Django"
known_restframework = ["rest_framework"]
import_heading_future = "Future"
import_heading_restframework = "Rest Framework"
import_heading_thirdparty = "Third party"
import_heading_firstparty = "drf-serializer-prefetch"
import_heading_localfolder = "Local"
default_section = "FIRSTPARTY"
sections = [
  "FUTURE",
  "STDLIB",
  "DJANGO",
  "RESTFRAMEWORK",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]

[tool.mypy]
python_version = 3.9
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.*"]
ignore_errors = true

[tool.django-stubs]
django_settings_module = "tests.settings"

[tool.ruff]
ignore = ["E501"]
